<a href="https://colab.research.google.com/github/NagillaSannidhi/python/blob/main/Day13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
k=[4,2.5678,9,87.9999,40,'india']
k

[4, 2.5678, 9, 87.9999, 40, 'india']

In [3]:
pd.Series(k)

0          4
1     2.5678
2          9
3    87.9999
4         40
5      india
dtype: object

In [4]:
k=[4,2.5678,9,87.9999,40,]

In [5]:
k

[4, 2.5678, 9, 87.9999, 40]

In [6]:
pd.Series(k)

0     4.0000
1     2.5678
2     9.0000
3    87.9999
4    40.0000
dtype: float64

In [7]:
a=np.random.randint(20,50,(5,4))
a

array([[31, 46, 31, 25],
       [46, 27, 42, 41],
       [25, 48, 30, 20],
       [47, 23, 25, 31],
       [24, 24, 48, 32]])

In [9]:
a.ndim

2

In [11]:
a=np.random.randint(20,50,15)

pd.Series(a)

0     40
1     33
2     27
3     33
4     31
5     26
6     22
7     25
8     45
9     20
10    36
11    36
12    44
13    34
14    38
dtype: int64

In [13]:
s=pd.Series(a)
s

0     40
1     33
2     27
3     33
4     31
5     26
6     22
7     25
8     45
9     20
10    36
11    36
12    44
13    34
14    38
dtype: int64

In [14]:
s[0]

40

In [15]:
s[8]

45

In [16]:
s[4:10]

4    31
5    26
6    22
7    25
8    45
9    20
dtype: int64

In [17]:
b=np.random.randint(100,200,(6,5))
b

array([[127, 170, 189, 158, 134],
       [188, 172, 119, 131, 194],
       [186, 184, 180, 102, 123],
       [114, 143, 136, 195, 199],
       [188, 103, 184, 187, 144],
       [177, 111, 124, 183, 189]])

In [18]:
b.ndim

2

In [19]:
pd.DataFrame(b)

     0    1    2    3    4
0  127  170  189  158  134
1  188  172  119  131  194
2  186  184  180  102  123
3  114  143  136  195  199
4  188  103  184  187  144
5  177  111  124  183  189

In [21]:
df=pd.DataFrame(b)
df

     0    1    2    3    4
0  127  170  189  158  134
1  188  172  119  131  194
2  186  184  180  102  123
3  114  143  136  195  199
4  188  103  184  187  144
5  177  111  124  183  189

In [22]:
df=pd.DataFrame(b,columns=['roll','name','age','code','country'])
df

   roll  name  age  code  country
0   127   170  189   158      134
1   188   172  119   131      194
2   186   184  180   102      123
3   114   143  136   195      199
4   188   103  184   187      144
5   177   111  124   183      189

In [26]:
df=pd.DataFrame(b,columns=['roll','name','age','code','country'],index=['nafees','pooji','navanitha','meghana','nikhitha','sannidhi'])
df

           roll  name  age  code  country
nafees      127   170  189   158      134
pooji       188   172  119   131      194
navanitha   186   184  180   102      123
meghana     114   143  136   195      199
nikhitha    188   103  184   187      144
sannidhi    177   111  124   183      189

In [27]:
df.iloc[3]

roll       114
name       143
age        136
code       195
country    199
Name: meghana, dtype: int64

In [31]:
df.iloc[5]

roll       177
name       111
age        124
code       183
country    189
Name: sannidhi, dtype: int64

In [32]:
df.loc['nafees']

roll       127
name       170
age        189
code       158
country    134
Name: nafees, dtype: int64

In [34]:
df.iloc[2,4]

123

In [35]:
df.loc['nikhitha',['roll','code']]

roll    188
code    187
Name: nikhitha, dtype: int64

In [36]:
df.iloc[3,2:4]

age     136
code    195
Name: meghana, dtype: int64

In [42]:
df.iloc[[1,3,4]]

          roll  name  age  code  country
pooji      188   172  119   131      194
meghana    114   143  136   195      199
nikhitha   188   103  184   187      144

In [43]:
df.iloc[[0,5]]

          roll  name  age  code  country
nafees     127   170  189   158      134
sannidhi   177   111  124   183      189

In [44]:
df

           roll  name  age  code  country
nafees      127   170  189   158      134
pooji       188   172  119   131      194
navanitha   186   184  180   102      123
meghana     114   143  136   195      199
nikhitha    188   103  184   187      144
sannidhi    177   111  124   183      189

In [45]:
df.age

nafees       189
pooji        119
navanitha    180
meghana      136
nikhitha     184
sannidhi     124
Name: age, dtype: int64

In [46]:
df['age']

nafees       189
pooji        119
navanitha    180
meghana      136
nikhitha     184
sannidhi     124
Name: age, dtype: int64

In [47]:
df[['age','country']]

           age  country
nafees     189      134
pooji      119      194
navanitha  180      123
meghana    136      199
nikhitha   184      144
sannidhi   124      189

In [48]:
df.loc[['nafees','nikhitha'],['roll','code']]

          roll  code
nafees     127   158
nikhitha   188   187

In [49]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [50]:
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [51]:
sns.load_dataset('dots')

    align choice  time  coherence  firing_rate
0    dots     T1   -80        0.0    33.189967
1    dots     T1   -80        3.2    31.691726
2    dots     T1   -80        6.4    34.279840
3    dots     T1   -80       12.8    32.631874
4    dots     T1   -80       25.6    35.060487
..    ...    ...   ...        ...          ...
843  sacc     T2   300        3.2    33.281734
844  sacc     T2   300        6.4    27.583979
845  sacc     T2   300       12.8    28.511530
846  sacc     T2   300       25.6    27.009804
847  sacc     T2   300       51.2    30.959302

[848 rows x 5 columns]

In [55]:
sns.load_dataset('titanic')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [56]:
df1=sns.load_dataset('titanic')

In [57]:
type(df1)

pandas.core.frame.DataFrame

In [59]:
df1.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [60]:
df1.shape

(891, 15)