<a href="https://colab.research.google.com/github/NagillaSannidhi/python/blob/main/Day14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=sns.load_dataset('taxis')
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [3]:
df.info

<bound method DataFrame.info of                   pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0
...                  ...                 ...         ...       ...   ...
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West
1     0.00    0.0   9.30  yellow         cash  Upper West Side South
2     2.36    0.0  14.16  yellow  credit card          Alphabet City
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq
4     1.10    0.0  13.40  yellow  credit card           Midtown East
...    ...    ...    ...     ...          ...                    ...
6428  1.06    0.0   6.36   green  credit card      East Harlem North
6429  0.00    0.0  58.80   green  credit card                Jamaica
6430  0.00    0.0  17.30   green         cash    Crown Heights North
6431  0.00    0.0   6.80   green  credit card          East New York
6432  3.36    0.0  20.16   green  credit card            Boerum Hill

                          dropoff_zone pickup_borough dropoff_borough
0                  UN/Turtle Bay South      Manhattan       Manhattan
1                Upper West Side South      Manhattan       Manhattan
2                         West Village      Manhattan       Manhattan
3                       Yorkville West      Manhattan       Manhattan
4                       Yorkville West      Manhattan       Manhattan
...                                ...            ...             ...
6428              Central Harlem North      Manhattan       Manhattan
6429  East Concourse/Concourse Village         Queens           Bronx
6430                    Bushwick North       Brooklyn        Brooklyn
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn
6432                   Windsor Terrace       Brooklyn        Brooklyn

[6433 rows x 14 columns]>

In [4]:
df.sample(4)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
4946,2019-03-11 17:53:03,2019-03-11 18:06:24,2,1.97,10.5,2.96,0.0,17.76,yellow,credit card,Union Sq,Upper East Side South,Manhattan,Manhattan
3514,2019-03-05 12:07:18,2019-03-05 12:15:44,2,1.09,7.0,3.00,0.0,13.30,yellow,credit card,Sutton Place/Turtle Bay North,Upper East Side South,Manhattan,Manhattan
489,2019-03-08 16:26:52,2019-03-08 16:32:17,1,0.60,5.5,2.45,0.0,12.25,yellow,credit card,Midtown Center,Midtown South,Manhattan,Manhattan
5776,2019-03-01 16:41:26,2019-03-01 17:24:05,1,7.29,30.0,0.00,0.0,31.80,green,credit card,Flatbush/Ditmas Park,East New York,Brooklyn,Brooklyn

In [5]:
df.sample(9)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
2598,2019-03-08 18:15:25,2019-03-08 18:32:11,1,1.28,11.50,0.00,0.00,15.80,yellow,cash,Gramercy,Midtown Center,Manhattan,Manhattan
3368,2019-03-08 15:56:52,2019-03-08 16:08:57,1,2.20,10.00,3.30,0.00,16.60,yellow,credit card,Upper West Side South,Morningside Heights,Manhattan,Manhattan
2266,2019-03-08 05:59:56,2019-03-08 06:06:40,3,2.35,8.50,2.36,0.00,14.16,yellow,credit card,Upper West Side South,Central Harlem,Manhattan,Manhattan
290,2019-03-06 15:09:42,2019-03-06 15:19:00,1,0.77,7.00,2.06,0.00,12.36,yellow,credit card,Lincoln Square East,Clinton West,Manhattan,Manhattan
5840,2019-03-25 18:54:47,2019-03-25 19:39:23,1,22.51,60.52,0.00,5.76,66.78,green,credit card,Morrisania/Melrose,Baisley Park,Bronx,Queens
4736,2019-03-22 02:20:08,2019-03-22 02:28:19,1,1.40,7.50,2.25,0.00,13.55,yellow,credit card,Midtown Center,Clinton East,Manhattan,Manhattan
4427,2019-03-02 08:49:02,2019-03-02 08:58:21,1,1.83,8.50,0.00,0.00,11.80,yellow,cash,Midtown Center,Lenox Hill East,Manhattan,Manhattan
5757,2019-03-13 15:39:47,2019-03-13 15:51:00,1,2.67,10.50,2.26,0.00,13.56,green,credit card,Flushing,Whitestone,Queens,Queens
3756,2019-03-05 20:00:10,2019-03-05 20:02:16,1,0.09,3.50,0.00,0.00,7.30,yellow,cash,TriBeCa/Civic Center,TriBeCa/Civic Center,Manhattan,Manhattan

In [6]:
df.head(15)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,18.80,yellow,credit card,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
7,2019-03-22 12:47:13,2019-03-22 12:58:17,0,1.40,8.5,0.00,0.0,11.80,yellow,NaN,Murray Hill,Flatiron,Manhattan,Manhattan
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.0,1.00,0.0,19.30,yellow,credit card,East Harlem South,Midtown Center,Manhattan,Manhattan
9,2019-03-08 16:18:37,2019-03-08 16:26:57,1,1.52,8.0,1.00,0.0,13.30,yellow,credit card,Lincoln Square East,Central Park,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.00,0.0,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
11,2019-03-20 19:39:42,2019-03-20 19:45:36,1,1.53,6.5,2.16,0.0,12.96,yellow,credit card,Upper West Side South,Manhattan Valley,Manhattan,Manhattan
12,2019-03-18 21:27:14,2019-03-18 21:34:16,1,1.05,6.5,1.00,0.0,11.30,yellow,credit card,Murray Hill,Midtown Center,Manhattan,Manhattan
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.5,0.00,0.0,13.80,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.5,0.00,0.0,14.80,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan

In [7]:
df.tail(7)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6426,2019-03-28 08:04:47,2019-03-28 08:07:46,1,0.71,4.5,0.50,0.0,5.80,green,credit card,Central Park,Upper West Side North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [10]:
df['color']

0       yellow
1       yellow
2       yellow
3       yellow
4       yellow
         ...
6428     green
6429     green
6430     green
6431     green
6432     green
Name: color, Length: 6433, dtype: object

In [11]:
df['color'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
6428    False
6429    False
6430    False
6431    False
6432    False
Name: color, Length: 6433, dtype: bool

In [12]:
df['payment'].isnull().sum()

44

In [13]:
df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [14]:
df['color'].isnull().sum()

0

In [15]:
df.shape[0]

6433

In [16]:
(df.isnull().sum()/df.shape[0])*100

pickup             0.000000
dropoff            0.000000
passengers         0.000000
distance           0.000000
fare               0.000000
tip                0.000000
tolls              0.000000
total              0.000000
color              0.000000
payment            0.683973
pickup_zone        0.404166
dropoff_zone       0.699518
pickup_borough     0.404166
dropoff_borough    0.699518
dtype: float64

missing data handling

1.Imputation (fill in the blanks)

  a)statistical measures

  b)Parameter

2.delete data

  rows

 columns

In [17]:
df.drop('pickup_zone',axis=1)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [19]:
df.drop(['pickup','color','payment','total'],axis=1,inplace=True)

In [20]:
df

,dropoff,passengers,distance,fare,tip,tolls,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [21]:
a=np.random.randint(10,50,15)

In [22]:
a

array([33, 36, 18, 31, 45, 44, 47, 20, 30, 16, 47, 13, 46, 46, 44])

In [23]:
df.iloc[100]

dropoff            2019-03-28 11:49:30
passengers                           1
distance                          1.79
fare                              13.5
tip                               3.36
tolls                              0.0
pickup_zone        Lincoln Square East
dropoff_zone             Midtown South
pickup_borough               Manhattan
dropoff_borough              Manhattan
Name: 100, dtype: object